### ISSUE TITLE
Adapt to .m2 cache improvements from deployer SPI project

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#114]
As a developer, I'd like to adapt the cf-deployer with deployer SPI changes pertaining to maven repository cleanup.

**Comment by ericbottard** [comment]
Invalid, this will be implemented in cf server (tracked via https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/233)
