### ISSUE TITLE
Move Spring related environment variables into SPRING_APPLICATION_JSON

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-deployer-cloudfoundry#12]
Certain apps have very complex property settings which are confused by Cloud Foundry's handling of environment variables.

Include a flag that instructs the deployer to first serialize the environment variables into a JSON structure and then write it into SPRING_APPLICATION_JSON instead of separate variables.

**Comment by markpollack** [comment]
This all or nothing approach isn't ideal.  A middle ground would be for any environment variables that start with `SPRING_` we put those into `SPRING_APPLICATION_JSON` - removing them from the original env-vars map, leaving the rest of the environment variable alone.  There can be other third party libraries that are directly trying to access env-vars and we would break those apps.

**Comment by gregturn** [comment]
I'm unsure of something that vague. Sounds like trying to automatically move certain "spring-y" things into SPRING_APPLICATION_JSON.

I'm in favor of something deliberate like "spring_application_json.":

* spring_application_json.THIS_PROP
* spring_application_json.that.prop
* but.not.this.one
* NOR_THIS_ONE
