### ISSUE TITLE
Introduce new option for "overall deployment" timeout

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer-cloudfoundry#125]
We should retrofit `CloudFoundryDeploymentProperties.apiTimeout` to be the "short API calls timeout" (default 1s) and use that everywhere except when long running operations are expected:
* app deploy
* task launch

For those two cases, introduce a new variable (on the same class) that conveys the idea of running an app (we may want to avoid `launch` and `deploy` wordings, which are task and app related at the moment).

**Comment by markpollack** [comment]
I had created this issue (in the wrong place - https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/256 ) with a bit more detail.

**Comment by markpollack** [comment]
after further discussion, add a new statusTimeout @ConfigurationProperty that would be used for stream/task status operations.
