### ISSUE TITLE
Add support for Docker based tasks

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer-cloudfoundry#164]
Seems like the 1.9+ version of the deployer could benefit from this (not sure about the old APIs).

**Comment by sabbyanandan** [comment]
We say a minimum of PCF 1.9 for Tasks in general, so we don't have to worry about older release/APIs.

**Comment by trisberg** [comment]
LGTM, I was able to run some docker apps in CF on PCF, and after setting the following env vars on the server I even got the task executions to show up in the UI/Shell:

```
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES: mysql
    SPRING_DATASOURCE_URL: '${vcap.services.mysql.credentials.jdbcUrl}'
    SPRING_DATASOURCE_USERNAME: '${vcap.services.mysql.credentials.username}'
    SPRING_DATASOURCE_PASSWORD: '${vcap.services.mysql.credentials.password}'
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'org.mariadb.jdbc.Driver'
```

I wonder if we should add this to the CF docs for SCDF.

**Comment by sabbyanandan** [comment]
@trisberg Sure thing! This would be the perfect place for this content: http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.0.M2/reference/htmlsingle/#_deploying_docker_applications - I will add a doc story.

**Comment by ericbottard** [comment]
Imho we should really not encourage running java/boot apps as docker
images. We lose all the benefits of buildpack / autoreconfiguration

Le 28 mars 2017 9:03 PM, "Thomas Risberg" <notifications@github.com> a
écrit :
