### ISSUE TITLE
Improve mapping for apps that are effectively in 'crashed' state

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-cloudfoundry#18]
The default retry attempts for 

```
case "CRASHED":
  return DeploymentState.failed;
```

is very long, certainly more than 3 hrs and heard it maybe weeks, so it is really never reached in practice for a dataflow deployment.  We should introduce our own logic to keep track of how many deployment attempts were made and then decide to fail the deployment state after our own threshold is reached.  This is done in the kubernetes deployer.

**Comment by gregturn** [comment]
I lean towards a time-based duration instead of pure counts.

**Comment by ericbottard** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/a3696a4077ebcae0fcfc6f791d19b66786ab6807
