### ISSUE TITLE
Make TaskLauncherTests.testStatusTimeout more robust

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer-cloudfoundry#197]
This has been failing sparingly on CI environments.

**Comment by ericbottard** [comment]
See https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/a6aeb16aeaf488789154a3ec5baa8e0f837b62a7 as a first attempt.

May use StepVerifier from reactor as well, maybe

**Comment by markpollack** [comment]
This issue has not come up in recent CI environmental testing, so closing
