### ISSUE TITLE
Harmonise @ConfigurationProperties with spring-cloud-cloudfoundry

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-deployer-cloudfoundry#21]
E.g. "organization"->"org", "api"->"url".

**Comment by markpollack** [comment]
Is this to sync w/ this specific class

https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/master/spring-cloud-cloudfoundry-discovery/src/main/java/org/springframework/cloud/cloudfoundry/discovery/CloudFoundryDiscoveryProperties.java

Note, before merging this PR, the docs will need to be updated (as it is a breaking change) and the CI job prop values also changed to the new names.
