### ISSUE TITLE
Silent failure when app name is too long

### ISSUE THREAD

**Issue by taavo** [spring-cloud/spring-cloud-deployer-cloudfoundry#210]
We deployed our dataflow server as `project-name-dataflow-server`, and then tried to create a stream as `the-name-of-our-background-job`. With the random bits in the middle, this produced app names for our stream components longer than 63 characters, which were then truncated (e.g. "project-name-dataflow-server-0953yn3t-the-name-of-our-"). One app of the stream was deployed successfully, but then the other failed without feedback.

It'd be great to have some sort of warning when this has happened or is about to happen. Thanks!

**Comment by ericbottard** [comment]
Hi @taavo .

I was able to deploy a stream made of simple apps (`time | log`) that used long app names, getting truncated without problem. You state that your app names **did** get truncated as well, so I believe the failure to start is unrelated to long names.

Would you by any chance have a stacktrace detailing the failure?

**Comment by sabbyanandan** [comment]
The lengthy app-names are captured, sanitized, and orchestrated to be within limits and we have verified that. @taavo: If you still see any anomaly with this, please reopen it. Logs would be useful to troubleshoot it.
