### ISSUE TITLE
Make the deletion of a route when deleting an application configurable.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-cloudfoundry#213]
When doing 'update' app operations, e.g deploy new app, delete old app, it can be useful to avoid deleting the route of the app (assuming the both apps have the same route name).

**Comment by ericbottard** [comment]
Ah ah, turns out this is not trivial at all.
The reason being that `undeploy()` doesn't take (deployment) properties or anything. It just accepts the id to be undeployed.

So the best we could do I guess is a global flag? Maybe that's ok for skipper?
