### ISSUE TITLE
Add a CI plan for PCF 1.12

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#219]
As a developer, I'd like to add a CI plan to run the TCK against PCF 1.12.

(_Note: `sepia` is now repaved with 1.12 with rabbit, redis, and, mysql services_)

**Comment by sobychacko** [comment]
CI plan is created: https://build.spring.io/browse/SCD-DCF-BCFDP1P-570
