### ISSUE TITLE
Update default java-buildpack version to the latest

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#297]
Though overridable (typically _always_ is), It appears that we are defaulting to an old [java-buildpack](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java#L95). It'd be good to default to the [latest](https://github.com/cloudfoundry/java-buildpack/releases).

**Comment by sabbyanandan** [comment]
@jvalkeal @ilayaperumalg - do we want to bite this in 2.2GA?

**Comment by ilayaperumalg** [comment]
@sabbyanandan yeah, it would be nice to have the latest. But, I would prefer not to update the code at this point of time (as we are wrapping up the SCDF 2.2.0 GA in a couple of days). The users still have the option to override the `buildpack` via deployment property if there is a need to use the latest.
