### ISSUE TITLE
Implement AppDeployer using the v2 CF API

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-cloudfoundry#3]
As a developer I would like to implement the AppDeployer SPI using the v2 CF library in an 'operator'/'higher level' API style.  

Acceptance criteria are unit tests that has coverage similar to the current v1 API.  A manual test of deploying time | log is also required.

**Comment by gregturn** [comment]
@nebhale says the -operations module is the way to go and that "push" is almost there. Until then, we don't have a create app op. 

Should be able to hack an undeploy though.

**Comment by markpollack** [comment]
This work started in 3a4b4fa724382b9ddc2342ed24145242da3d541a and has evolved since.  This issue can now be closed.
