### ISSUE TITLE
How to specify multi buildpack for deployment?

### ISSUE THREAD

**Issue by myamith** [spring-cloud/spring-cloud-deployer-cloudfoundry#300]
In Spring data flow [deployment properties](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-cloudfoundry-deployer) can accept only single buildpack. What is the way/support for multibuildpack for example Java-buildpack,python-buildpack.

**Comment by sabbyanandan** [comment]
Questions like this are better suited for StackOverflow or Gitter. Please consider asking in those forums going forward.

That said, the CF-deployer _uses_ the [cf-java-client](https://github.com/cloudfoundry/cf-java-client) to interact with the Cloud Controller to deploy applications and bind to the desired managed services in the platform. Likewise, SCDF provides an option to deploy Spring Boot uber-jars. And, they are expected to be Java applications. 

If you intend to run Python applications via SCDF, you can use the [polyglot recipe](https://dataflow.spring.io/docs/recipes/polyglot/) that we have for K8s. You can, of course, alter it to run it in PCF as well.

Lastly, it'd be great if you can describe the use-cases, so we can relate to why you'd want an application with both Java and Python buildpacks. What is the purpose of this app? Can you share a sample?

**Comment by myamith** [comment]
Use case is deploy a python app as a task in SCDF and constraint is not to use docker in PCF

**Comment by sabbyanandan** [comment]
Unfortunately, native Python workloads **without** Docker is not the scope of this project. 

Mainly, for Tasks, we track task-execution and transaction statistics, and they are expected to be either the Spring Cloud Task and/or Spring Batch schemas. For native Python workloads, it won't work out-of-the-box, so none of the value-adds would work.

Our primary focus and the value proposition in PAS revolves around Spring Boot applications.
