### ISSUE TITLE
Group should be optional

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-deployer-cloudfoundry#32]
Or maybe not even explicit (should be the concern of the caller).

**Comment by markfisher** [comment]
"group" could be a first class concept within the Deployer SPI if we want to extend some functionality, such as checking the status of a group of apps or managing the lifecycle of a group of apps... otherwise, we might end up with several different callers managing those concerns

**Comment by gregturn** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/19

**Comment by sabbyanandan** [comment]
This is already addressed via: #19
