### ISSUE TITLE
Delete application artifacts after successful deployment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#322]
As an SCDF user, while continuously resolving new application versions via http/maven resolution, I notice the disk-quota attached with SCDF/Skipper servers reaches the upper limit and the servers crash. This is quickly reproducible in CF, in particular since the allocated disk-quota for SCDF can go up to a max of 2G.

**Acceptance:**
- Add a new property to toggle  to flag the deletion of application artifacts after successful stream and task deployments (maybe: `spring.cloud.deplolyer.deleteDownloadedArtifact` or similar)
- Unless the property is overridden, delete the application by default 
- Delete also the metadata JAR along with the application - clean slate it all!
- Decide how to implement this specifically for CF-deployer (however, the application resolution code is in SPI)
- Design how to expose the new property as a global setting in SCDF 
- Tests included

**Comment by dturanski** [comment]
Currently, it appears that we always do this.  Need to investigate further.
