### ISSUE TITLE
Support environment variable as a CF deployer property

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-cloudfoundry#325]
As a user, I'd like to set the CF environment variable as a CF deployer property.

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/311.

**Comment by sabbyanandan** [comment]
We would still want to have a deployer property, but #311 is a specific example of its use. Reopening it.
