### ISSUE TITLE
Allow task scheduling extensibility (to support non-pivotal cloud foundry deployments)

### ISSUE THREAD

**Issue by dbahatSAP** [spring-cloud/spring-cloud-deployer-cloudfoundry#328]
Currently the CloudFoundryAppScheduler has a single implementation which explicitly uses io.pivotal.scheduler.
The idea is to allow a runtime dependency to replace the scheduler implementation. This would enable dependent projects (SCDF) to support task scheduling also on non-pivotal cloud foundry deployments.

**Comment by markpollack** [comment]
Long time no comment, but we are not looking to directly integrate any other schedulers into the deployer.  More sophisticated schedulers can be used by interacting with the Data Flow REST API
