### ISSUE TITLE
Support recreating TokenProvider

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-deployer-cloudfoundry#350]
As CFJC currently doesn't re-login when refresh token expires we should do an attempt to re-create a `TokenProvider` to force a re-login. This is a further work for this which started with #348.

Add new `RecreatingTokenProvider` and `tokenProviderValidity` connection property. Validity duration in seconds should be set to be smaller than than UAA's token refresh validity as then re-login happens before invalid refresh token is used.

**Comment by sabbyanandan** [comment]
The [CFJC fix](https://github.com/cloudfoundry/cf-java-client/commit/0cea1e03f98292dbe38ac108eb8efad0b87ff814) is available in the `4.8.0.BUILD-SNAPSHOT`; let's pull that in and run the CF ATs.

**Comment by sabbyanandan** [comment]
We still haven't upgraded yet to 4.8 BS. @jvalkeal: Can we please switch this soon?
