### ISSUE TITLE
Allow the request to override buildpack on deployment

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-deployer-cloudfoundry#36]
Buildpack, mem, and disk are only set via fixed configuration properties. Overriding on a per request basis is critical to usage in a multithreaded system.

**Comment by markpollack** [comment]
I believe only the buildpack isn't configurable on a per-request basis now.

**Comment by markpollack** [comment]
I do not see any multithreading concerns here.

Memory and disk can currently be set per deployment request using the properties `spring.cloud.deployer.cloudfoundry.memory` and `spring.cloud.deployer.cloudfoundry.disk` as defined in `CloudFoundryAppDeployer`. This setting applies across all the deployed applications in a stream.

I will change the title to reference a global change to the buildpack.

Setting memory/disk properties per application in a stream will be handled once  https://github.com/spring-cloud/spring-cloud-deployer/issues/69 is completed and will be part of another issue.

**Comment by ericbottard** [comment]
Fixed by 3a8fd23a6a7186abf7e3a02455b4d3334a0ee757

I think I mistakenly closed the -spinnaker issue with same number before
