### ISSUE TITLE
maven remote repositories settings

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud/spring-cloud-deployer-cloudfoundry#75]
Hey there.  So, in working on trying to externalize configuration info in a properties file, and then use Spring Cloud Config Server to provide these environment settings at installation time, I'm got a question about some of the values I would normally put a certain way in the YML manifest. 

First, in a YML manifest, I might define them this way: 
```
JAVA_OPTS: -Dhttp.keepAlive=false
MAVEN_REMOTE_REPOSITORIES_SNAPSHOTS_URL: <nexus url>
MAVEN_REMOTE_REPOSITORIES_RELEASES_URL: <another nexus url>
```

So how would I put these into a properties file?  This is my guess: 
```
java.opts=-Dhttp.keepAlive=false
maven.remote.repositories.snapshots.url=<nexus url>
maven.remote.repositories.releases.url=<another nexus url>
```

**Comment by ericbottard** [comment]
See answer at http://stackoverflow.com/questions/39027446/spring-cloud-deployer-specifying-maven-remote-repository-urls
