### ISSUE TITLE
Deployer is not sharing the database

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#95]
As a user, I'm using the deployer in SCDF-CF-Server with a commonly bound `mysql` service with the hope to reuse the database for stream/task metadata and task/job executions. With this setup, I'm unable to reuse the same datasource. The apps launched by the deployer are bound to a complete different database instance.

**Comment by sabbyanandan** [comment]
Turns out, the default timeout setting was the root-cause for this error. When the async operation to launch the task times out, the application is at an inconsistent stage in the lifecycle and upon re-launch, the application continues from where it stopped and the boot configuration kicks in with a complete new datasource instance.

**Comment by markpollack** [comment]
I believe this works if you use the properties described in http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.0.0.RELEASE/reference/htmlsingle/#getting-started-service-binding-at-application-level

What I think we need is the introduction of the property `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES` for the SCDF Server (which is there for streams) that will be used always bind the DB

**Comment by sabbyanandan** [comment]
We have been using `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES` to supply service bindings for task applications. For instance, following is what I used in pcfdev. 

```
    SPRING_APPLICATION_NAME: sabby-dataflow-server
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: https://api.local.pcfdev.io
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: pcfdev-org
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: pcfdev-space
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: local.pcfdev.io
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: redis,rabbit,mysql
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES: mysql
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_DISK: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: admin
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: admin
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true
    MAVEN_REMOTE_REPOSITORIES_REPO1_URL: https://repo.spring.io/libs-snapshot
    SPRING_CLOUD_DATAFLOW_FEATURES_EXPERIMENTAL_TASKSENABLED: true
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: false
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_TASK_TIMEOUT: 30000
```

The core premise of this issue was due to timeouts, though - see my previous comment. Confirmed the behavior in both pcfdev/pws.

**Comment by markpollack** [comment]
Hmm, I thought we were missing that variable.... TASK_SERVICES, guess not.
