### ISSUE TITLE
PWS Task API has changed

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-cloudfoundry#98]
PWS and PCF now have incompatible APIs.  Ideally we need to support both.  Need to figure out a way.  See https://build.spring.io/browse/SCD-DCF-BSCD-148/test/case/205231777 for test failure.

**Comment by ericbottard** [comment]
This has been fixed in 77729e5861a20d171e1b46ced018a88067852a15
